import React, { useState, useEffect } from 'react';
import { Clock, Repeat, TrendingUp, BookOpen, Zap, CalendarCheck, Download, CheckCircle2, Circle, Calendar } from 'lucide-react';
import { LearningAnalysis } from '../types';
import { RetentionChart } from './RetentionChart';

interface ResultsDashboardProps {
  data: LearningAnalysis;
}

export const ResultsDashboard: React.FC<ResultsDashboardProps> = ({ data }) => {
  const [completedSessions, setCompletedSessions] = useState<number[]>([]);

  // Load completed sessions from local storage specifically for this topic if available
  useEffect(() => {
    const saved = localStorage.getItem(`cogniplan_progress_${data.topic.substring(0, 10)}`);
    if (saved) {
      setCompletedSessions(JSON.parse(saved));
    } else {
      setCompletedSessions([]);
    }
  }, [data.topic]);

  const toggleSession = (sessionNumber: number) => {
    const updated = completedSessions.includes(sessionNumber)
      ? completedSessions.filter(n => n !== sessionNumber)
      : [...completedSessions, sessionNumber];
    
    setCompletedSessions(updated);
    localStorage.setItem(`cogniplan_progress_${data.topic.substring(0, 10)}`, JSON.stringify(updated));
  };

  const handleDownload = () => {
    const content = `
STUDY PLAN: ${data.topic}
Generated by CogniPlan
------------------------------------------------
Total Time: ${data.estimatedMinutesTotal} min
Difficulty: ${data.difficultyRating}
------------------------------------------------

SCHEDULE:
${data.studyPlan.map(s => `
[${completedSessions.includes(s.sessionNumber) ? 'X' : ' '}] Session ${s.sessionNumber} (${s.intervalLabel})
   Method: ${s.method}
   Focus: ${s.focusDescription}
   Duration: ${s.durationMinutes} min
`).join('')}

------------------------------------------------
RATIONALE:
${data.scientificRationale}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `StudyPlan-${data.topic.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCalendarDownload = () => {
    let icsContent = `BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//CogniPlan//Study Schedule//EN\n`;
    const today = new Date();

    data.studyPlan.forEach(session => {
      const sessionDate = new Date(today);
      // Fallback to rough estimate if dayOffset is missing from older generations
      const offset = typeof session.dayOffset === 'number' 
        ? session.dayOffset 
        : [0, 1, 3, 7, 14, 30][session.sessionNumber - 1] || (session.sessionNumber * 7);
      
      sessionDate.setDate(today.getDate() + offset);
      
      // Format date YYYYMMDD
      const dateStr = sessionDate.toISOString().split('T')[0].replace(/-/g, '');
      
      icsContent += `BEGIN:VEVENT\n`;
      icsContent += `DTSTART;VALUE=DATE:${dateStr}\n`;
      icsContent += `SUMMARY:Study ${data.topic} - Session ${session.sessionNumber}\n`;
      icsContent += `DESCRIPTION:Method: ${session.method}\\nFocus: ${session.focusDescription}\\nRepetition #${session.sessionNumber}\n`;
      icsContent += `END:VEVENT\n`;
    });

    icsContent += `END:VCALENDAR`;

    const blob = new Blob([icsContent], { type: 'text/calendar' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CogniPlan-${data.topic.replace(/\s+/g, '_')}.ics`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center text-center hover:shadow-md transition-shadow">
          <div className="p-3 bg-blue-50 text-blue-600 rounded-full mb-3">
            <Clock size={24} />
          </div>
          <span className="text-slate-500 text-xs font-bold uppercase tracking-wider">Total Time</span>
          <span className="text-2xl font-display font-bold text-slate-900">{data.estimatedMinutesTotal} min</span>
          <span className="text-xs text-slate-400 mt-1">Active Focus Required</span>
        </div>

        <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center text-center hover:shadow-md transition-shadow">
          <div className="p-3 bg-purple-50 text-purple-600 rounded-full mb-3">
            <Repeat size={24} />
          </div>
          <span className="text-slate-500 text-xs font-bold uppercase tracking-wider">Spaced Reps</span>
          <span className="text-2xl font-display font-bold text-slate-900">{data.recommendedRepetitions}</span>
          <span className="text-xs text-slate-400 mt-1">Optimal Sessions</span>
        </div>

        <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center text-center hover:shadow-md transition-shadow">
          <div className="p-3 bg-emerald-50 text-emerald-600 rounded-full mb-3">
            <TrendingUp size={24} />
          </div>
          <span className="text-slate-500 text-xs font-bold uppercase tracking-wider">Complexity</span>
          <span className="text-2xl font-display font-bold text-slate-900">{data.difficultyRating}</span>
          <span className="text-xs text-slate-400 mt-1">Cognitive Load</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column: Plan Timeline */}
        <div className="lg:col-span-2 bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
          <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
            <h2 className="text-lg font-display font-bold text-slate-800 flex items-center">
              <CalendarCheck className="w-5 h-5 mr-2 text-brand-500" />
              Optimization Schedule
            </h2>
            <div className="flex gap-2">
              <button 
                onClick={handleCalendarDownload}
                className="text-xs flex items-center text-slate-600 font-medium bg-slate-50 hover:bg-slate-100 border border-slate-200 px-3 py-1.5 rounded-lg transition-colors"
                title="Add to Calendar (Google/Outlook/Apple)"
              >
                <Calendar className="w-3.5 h-3.5 mr-1.5" />
                Add to Calendar
              </button>
              <button 
                onClick={handleDownload}
                className="text-xs flex items-center text-brand-600 font-medium bg-brand-50 hover:bg-brand-100 px-3 py-1.5 rounded-lg transition-colors"
              >
                <Download className="w-3.5 h-3.5 mr-1.5" />
                Text File
              </button>
            </div>
          </div>

          <div className="relative border-l-2 border-slate-100 ml-3 space-y-8">
            {data.studyPlan.map((session, idx) => {
              const isCompleted = completedSessions.includes(session.sessionNumber);
              return (
                <div key={idx} className="relative pl-8">
                  {/* Timeline Dot */}
                  <div className={`absolute -left-[9px] top-0 w-4 h-4 rounded-full border-2 transition-colors ${isCompleted ? 'bg-brand-500 border-brand-500' : 'bg-white border-brand-500'}`}></div>
                  
                  <div 
                    onClick={() => toggleSession(session.sessionNumber)}
                    className={`cursor-pointer flex flex-col sm:flex-row sm:items-start sm:justify-between bg-slate-50 p-4 rounded-xl hover:bg-brand-50 transition-all group border-2 ${isCompleted ? 'border-brand-200 bg-brand-50/50' : 'border-transparent'}`}
                  >
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-xs font-bold bg-slate-200 text-slate-700 px-2 py-0.5 rounded uppercase">
                          {session.intervalLabel}
                        </span>
                        <span className="text-xs font-medium text-slate-400">
                          Session {session.sessionNumber}
                        </span>
                        {isCompleted && <span className="text-xs font-bold text-brand-600 flex items-center"><CheckCircle2 className="w-3 h-3 mr-1"/> Done</span>}
                      </div>
                      <h3 className={`font-bold mb-1 group-hover:text-brand-700 ${isCompleted ? 'text-brand-900 line-through opacity-70' : 'text-slate-900'}`}>{session.method}</h3>
                      <p className={`text-sm leading-relaxed ${isCompleted ? 'text-brand-700/70' : 'text-slate-600'}`}>{session.focusDescription}</p>
                    </div>
                    <div className="mt-3 sm:mt-0 sm:ml-4 flex flex-col items-end gap-2">
                      <div className="flex items-center text-slate-500 font-medium text-sm whitespace-nowrap">
                        <Clock className="w-4 h-4 mr-1" />
                        {session.durationMinutes} min
                      </div>
                      <div className="text-slate-300 group-hover:text-brand-400 transition-colors">
                        {isCompleted ? <CheckCircle2 className="w-5 h-5 text-brand-500" /> : <Circle className="w-5 h-5" />}
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Column: Science & Insights */}
        <div className="space-y-6">
            {/* Chart */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
                <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Retention Projection</h3>
                <RetentionChart reps={data.recommendedRepetitions} />
                <p className="text-xs text-slate-400 mt-3 text-center italic">
                    Projected memory decay vs. reinforcement (Ebbinghaus)
                </p>
            </div>

            {/* Rationale */}
            <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl shadow-lg p-6 text-white">
                <div className="flex items-center gap-2 mb-3 text-brand-300">
                    <Zap size={20} />
                    <h3 className="font-bold uppercase tracking-wide text-sm">Why this works</h3>
                </div>
                <p className="text-sm text-slate-300 leading-relaxed opacity-90">
                    {data.scientificRationale}
                </p>
            </div>

            {/* Key Concepts */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
                <div className="flex items-center gap-2 mb-4 text-slate-700">
                    <BookOpen size={20} />
                    <h3 className="font-bold">Key Concepts to Chunk</h3>
                </div>
                <div className="flex flex-wrap gap-2">
                    {data.keyConcepts.map((concept, i) => (
                        <span key={i} className="px-3 py-1 bg-slate-100 text-slate-700 text-sm rounded-full border border-slate-200">
                            {concept}
                        </span>
                    ))}
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};